### PR TITLE
setting up postgressql

### PR DESCRIPTION
**Pull request by RadiactiveJesus**

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi Team, this project is coming along properly. More gems need to be added though

Devise gem and Omni-auth gem

**IMPORTANT** make descriptive pull requests with messages
**IMPORTANT** make stickler work for this project

Please make changes and request for a re-review

**RAPHAEL NORIODE**

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team, 
## **Great work making almost all the necessary corrections from the previous review.** :+1: 
**Just one more thing to do guys** :slightly_smiling_face: , which is `adding stickler config`, previous reviewer talked about but for some reason you are yet to add it.
Kindly add linter's check and fix all errors if need too, checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
image
If you are not having this check on your `Github` page, kindly visit :point_right:[ linter set up](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)

Kindly re-submit for review after making this changes :slightly_smiling_face: Thumps -up await you.....

**Comment by RadiactiveJesus** [comment]
> Hi Team,
> 
> ## **Great work making almost all the necessary corrections from the previous review.** 👍
> **Just one more thing to do guys** 🙂 , which is `adding stickler config`, previous reviewer talked about but for some reason you are yet to add it.
> Kindly add linter's check and fix all errors if need too, checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
> image
> If you are not having this check on your `Github` page, kindly visit 👉[ linter set up](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)
> 
> Kindly re-submit for review after making this changes 🙂 Thumps -up await you.....

Hello Oluwaseun, I had troubles setting it up, I believe is because the repository belongs to my partner, and he is not longer on the program. Im running the linter config in my locla environment still

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required 

Hi @RadiactiveJesus and @i4seeu 👋,

You guys did a great job so far. However, you are still missing one of the required gems to get the 👍 :
`omniauth-facebook`

**I accept your reasoning for the linter, but please consider maybe doing the project in your own repo since your partner has left! Are you going to be repaired with another student soon or do you have permission to continue solo?**

#### Suggested changes [OPTIONAL]
- [OPTIONAL] Consider adding RSpec as well since you'd need it for the next milestone.
Here are some resources on RSpec for rails:
https://github.com/rspec/rspec-rails
https://relishapp.com/rspec/rspec-rails/v/3-8/docs 
https://thoughtbot.com/blog/how-we-test-rails-applications (This references FactoryGirl, which is now FactoryBot)
https://www.youtube.com/watch?v=UggLiefD02Q (Video on the older side but still useful)
**If you would like shared access to an additional book resource, contact me on slack and I'd gladly share**

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by RadiactiveJesus** [comment]
> 
> # Changes Required
> 
> Hi @RadiactiveJesus and @i4seeu 👋,
> 
> You guys did a great job so far. However, you are still missing one of the required gems to get the 👍 :
> `omniauth-facebook`
> 
> **I accept your reasoning for the linter, but please consider maybe doing the project in your own repo since your partner has left! Are you going to be repaired with another student soon or do you have permission to continue solo?**
> #### Suggested changes [OPTIONAL]
> 
>     * [OPTIONAL] Consider adding RSpec as well since you'd need it for the next milestone.
>       Here are some resources on RSpec for rails:
>       https://github.com/rspec/rspec-rails
>       https://relishapp.com/rspec/rspec-rails/v/3-8/docs
>       https://thoughtbot.com/blog/how-we-test-rails-applications (This references FactoryGirl, which is now FactoryBot)
>       https://www.youtube.com/watch?v=UggLiefD02Q (Video on the older side but still useful)
>       **If you would like shared access to an additional book resource, contact me on slack and I'd gladly share**
> 
> 
> _**Please makes changes and submit another review request. If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**_
> 
> _Happy coding 😄,_
> **[--Maya](https://github.com/mcrd25)**
> [GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)
> 
> _P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **

**Review by JamesOkunlade — APPROVED** [review]
# Approved 👍 😄 

**Great job so far. You can go ahead and merge this milestone.**

Good luck with the next milestone

**James Okunlade**
**Happy coding! 😎**

**Pull request merged**
